# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Marketing for Lawyers
business_title: Case Linguist LLC
marketing_title: Marketing for Lawyers
email: rene@marketingforlawyers.org
description: > # this means to ignore newlines until "baseurl:"
  Contact a Chicago-based SEO company specializing in legal marketing for English and Spanish speaking audiences.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://marketingforlawyers.org" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: caselinguist
github_username:  caselinguist
google_analytics: UA-93007789-1


# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock


# Blog settings
show_excerpts: true
default_lang: "en"
# exclude_from_localization: ["javascript", "images", "css"]

# global permalink settings
permalink: /:categories/:title-:month-:day-:year:output_ext

collections:
  pricing:
    output: true
    pricing_level: "comprehensive"
